### ISSUE TITLE
misurare il tempo tra start e end

### ISSUE THREAD

**Issue by danicampa90** [paolomorettin/worlds#9]

**Comment by danicampa90** [comment]
Per ora il tempo non viene misurato, ma abbiamo il sistema con i trigger! :8ball: :sunglasses:

**Comment by paolomorettin** [comment]
Non ho capito bene cosa intendi. Comunque nella versione con solo irrlicht, avevo già implementato il timer (che si vedeva anche a video), potresti buttare un occhio alle vecchie versioni per avere un'idea! :)

**Comment by danicampa90** [comment]
Implementato
